services:

  shutter:
    build: 
      context: .
      dockerfile: src/shutter/Dockerfile
    restart: unless-stopped
    ports:
      - 5555:5555
    environment:
      - BUCKET_URL=http://bucketservice:9000
      - BUCKET_KEY=minioadmin
      - BUCKET_SECRET=minioadmin
      - TTS_KEY=${TTS_KEY}
      - TTS_REGION=${TTS_REGION}
      - SPEECH_CONDUCT_OCSP_CHECK=0

  bucketservice:
    image: minio/minio
    restart: unless-stopped
    ports:
      - 9001:9001
    command: server /data --console-address ":9001"