services:

  ytdlservice:
    container_name: ytdlservice
    build:
      context: src/ytdlservice
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - S3_URL=http://storage:9000
      - S3_KEY=minioadmin
      - S3_SECRET=minioadmin
    depends_on:
      - rabbitmq
      - storage

  remix:
    container_name: remix
    build:
      context: src/remix
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/remix
    command: npm run dev
    depends_on:
      - postgres

  storage:
    container_name: storage
    image: minio/minio
    ports:
      - 9001:9001 # web
    command: server /data --console-address ":9001"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672 # web

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
