services:

  ytdlservice:
    build:
      context: .
      dockerfile: src/ytdlservice/Dockerfile
    restart: unless-stopped
    environment:
      - RABBITMQ_URL=amqp://rabbitmqservice:5672
      - BUCKET_URL=http://bucketservice:9000
      - BUCKET_KEY=minioadmin
      - BUCKET_SECRET=minioadmin

  shutter:
    build: 
      context: .
      dockerfile: src/shutter/Dockerfile
    restart: unless-stopped
    ports:
      - 5555:5555
    environment:
      - BUCKET_URL=http://bucketservice:9000
      - BUCKET_KEY=minioadmin
      - BUCKET_SECRET=minioadmin
      - TTS_KEY=${TTS_KEY}
      - TTS_REGION=${TTS_REGION}
      - SPEECH_CONDUCT_OCSP_CHECK=0

  uploadservice:
    build:
      context: .
      dockerfile: src/uploadservice/Dockerfile
    restart: unless-stopped
    ports:
      - 8787:8787
    command: npx miniflare -b BUCKET_URL=http://bucketservice:9000 -b BUCKET_KEY=minioadmin -b BUCKET_SECRET=minioadmin index.js

  bucketservice:
    image: minio/minio
    restart: unless-stopped
    ports:
      - 9001:9001 # web
    command: server /data --console-address ":9001"

  rabbitmqservice:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 15672:15672 # web